language: java

jdk:
  - oraclejdk8
install: mvn clean install
sudo: true
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gdmmadhan@gmail.com
  password: bluemount84
  organization: Jigarthandaone
  space: development1
  on:
    repo: RaviParamasivan/DeveOpsDemo
